source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PWAlertController_Example', :exclusive => true do
  pod 'PWAlertController', :path => '../'
end

target 'PWAlertController_Tests', :exclusive => true do
  pod 'PWAlertController', :path => '../'

  
end
